# good s0.4
base: "./configs/base_config.yaml"

prompt_template: "masterpiece, best quality, intricate, print, pattern, {}"

third_party_dict:
  dreambooth: "./models/Model/disneyPixarCartoon_v10.safetensors"
  clip_skip: 2

num_inference_steps: 50
t_index_list: [30, 36, 42]
